### ISSUE TITLE
Organize Structure of Readme.md

### ISSUE THREAD

**Issue by dipakparmar** [truopensource/markdownintro#1]
Structure the README.MD for beginners.  
Objectives: 
- Easy to navigate topics (create an index and link to topics)
- Add more examples
- Any other suggestions, ping us at opensource@trusu.ca  

And don't forget to add your name at the bottom: 👍 
Contributors: Name @githubhandle

**Comment by felipehfs** [comment]
Hello, Can i help you?

**Comment by dipakparmar** [comment]
> Hello, Can i help you?

Sure! read the description for contribution.
